# ============================================================================
# Grafana Admin Credentials ExternalSecret
# ============================================================================
# This ExternalSecret syncs the Grafana admin password from AWS Secrets Manager
# to Kubernetes. The External Secrets Operator watches this resource and
# creates/updates the Kubernetes Secret "grafana-admin-credentials".
#
# Note: This requires updating kube-prom-stack.yaml to use existingSecret
# instead of a hardcoded adminPassword value.
#
# Prerequisites:
# - External Secrets Operator deployed (via Terraform)
# - ClusterSecretStore "aws-secrets-manager" created
# - Secrets uploaded to AWS Secrets Manager (via generate-and-upload-secrets.sh)
#
# To apply: kubectl apply -f apps/monitoring/grafana-external-secret.yaml
# To verify: kubectl describe externalsecret grafana-admin-credentials -n monitoring
# To check sync status: kubectl get externalsecret grafana-admin-credentials -n monitoring
# ============================================================================

apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: grafana-admin-credentials
  namespace: monitoring
  labels:
    app: grafana
    component: monitoring
    managed-by: external-secrets-operator
spec:
  # Refresh secrets from AWS Secrets Manager every hour
  refreshInterval: 1h

  # Reference to the ClusterSecretStore
  secretStoreRef:
    name: aws-secrets-manager
    kind: ClusterSecretStore

  # Target Kubernetes Secret to create/update
  target:
    name: grafana-admin-credentials
    creationPolicy: Owner
    template:
      type: Opaque
      data:
        # Grafana expects specific key names for existingSecret
        admin-user: admin
        admin-password: "{{ .password | toString }}"

  # Map AWS Secrets Manager secret to template variable
  data:
  - secretKey: password
    remoteRef:
      key: aiml-platform/monitoring/grafana-admin-password
