# ============================================================================
# DataHub MySQL ExternalSecret
# ============================================================================
# This ExternalSecret syncs the MySQL root password from AWS Secrets Manager
# to Kubernetes. The External Secrets Operator watches this resource and
# creates/updates the Kubernetes Secret "mysql-secrets".
#
# Prerequisites:
# - External Secrets Operator deployed (via Terraform)
# - ClusterSecretStore "aws-secrets-manager" created
# - Secrets uploaded to AWS Secrets Manager (via generate-and-upload-secrets.sh)
#
# To apply: kubectl apply -f apps/datahub-pre/mysql-external-secret.yaml
# To verify: kubectl describe externalsecret mysql-secrets -n datahub
# To check sync status: kubectl get externalsecret mysql-secrets -n datahub
# ============================================================================

apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: mysql-secrets
  namespace: datahub
  labels:
    app: datahub
    component: mysql
    managed-by: external-secrets-operator
spec:
  # Refresh secrets from AWS Secrets Manager every hour
  refreshInterval: 1h

  # Reference to the ClusterSecretStore
  secretStoreRef:
    name: aws-secrets-manager
    kind: ClusterSecretStore

  # Target Kubernetes Secret to create/update
  target:
    name: mysql-secrets
    creationPolicy: Owner
    template:
      type: Opaque

  # Map AWS Secrets Manager secret to Kubernetes Secret key
  data:
  - secretKey: mysql-root-password
    remoteRef:
      key: aiml-platform/datahub/mysql-root-password
