# ============================================================================
# DataHub Neo4j ExternalSecret
# ============================================================================
# This ExternalSecret syncs the Neo4j password from AWS Secrets Manager
# to Kubernetes. The External Secrets Operator watches this resource and
# creates/updates the Kubernetes Secret "neo4j-secrets".
#
# Note: This replaces the hardcoded "datahub" password previously used.
#
# Prerequisites:
# - External Secrets Operator deployed (via Terraform)
# - ClusterSecretStore "aws-secrets-manager" created
# - Secrets uploaded to AWS Secrets Manager (via generate-and-upload-secrets.sh)
#
# To apply: kubectl apply -f apps/datahub-pre/neo4j-external-secret.yaml
# To verify: kubectl describe externalsecret neo4j-secrets -n datahub
# To check sync status: kubectl get externalsecret neo4j-secrets -n datahub
# ============================================================================

apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: neo4j-secrets
  namespace: datahub
  labels:
    app: datahub
    component: neo4j
    managed-by: external-secrets-operator
spec:
  # Refresh secrets from AWS Secrets Manager every hour
  refreshInterval: 1h

  # Reference to the ClusterSecretStore
  secretStoreRef:
    name: aws-secrets-manager
    kind: ClusterSecretStore

  # Target Kubernetes Secret to create/update
  target:
    name: neo4j-secrets
    creationPolicy: Owner
    template:
      type: Opaque

  # Map AWS Secrets Manager secret to Kubernetes Secret key
  data:
  - secretKey: neo4j-password
    remoteRef:
      key: aiml-platform/datahub/neo4j-password
