# ============================================================================
# Langfuse ExternalSecret
# ============================================================================
# This ExternalSecret syncs secrets from AWS Secrets Manager to Kubernetes.
# The External Secrets Operator watches this resource and creates/updates
# the Kubernetes Secret "langfuse" with values from AWS Secrets Manager.
#
# Prerequisites:
# - External Secrets Operator deployed (via Terraform)
# - ClusterSecretStore "aws-secrets-manager" created
# - Secrets uploaded to AWS Secrets Manager (via generate-and-upload-secrets.sh)
#
# To apply: kubectl apply -f apps/langfuse/external-secret.yaml
# To verify: kubectl describe externalsecret langfuse -n langfuse
# To check sync status: kubectl get externalsecret langfuse -n langfuse
# ============================================================================

apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: langfuse
  namespace: langfuse
  labels:
    app: langfuse
    managed-by: external-secrets-operator
spec:
  # Refresh secrets from AWS Secrets Manager every hour
  refreshInterval: 1h

  # Reference to the ClusterSecretStore
  secretStoreRef:
    name: aws-secrets-manager
    kind: ClusterSecretStore

  # Target Kubernetes Secret to create/update
  target:
    name: langfuse
    creationPolicy: Owner
    template:
      type: Opaque

  # Map AWS Secrets Manager secrets to Kubernetes Secret keys
  data:
  - secretKey: salt
    remoteRef:
      key: aiml-platform/langfuse/salt

  - secretKey: encryption-key
    remoteRef:
      key: aiml-platform/langfuse/encryption-key

  - secretKey: nextauth-secret
    remoteRef:
      key: aiml-platform/langfuse/nextauth-secret

  - secretKey: postgresql-password
    remoteRef:
      key: aiml-platform/langfuse/postgresql-password

  - secretKey: clickhouse-password
    remoteRef:
      key: aiml-platform/langfuse/clickhouse-password

  - secretKey: redis-password
    remoteRef:
      key: aiml-platform/langfuse/redis-password

  - secretKey: s3-user
    remoteRef:
      key: aiml-platform/langfuse/s3-user

  - secretKey: s3-password
    remoteRef:
      key: aiml-platform/langfuse/s3-password
