# ============================================================================
# Langfuse Secret Configuration
# ============================================================================
# WARNING: This file contains secret values that MUST be generated uniquely
# for your deployment. DO NOT use the example values shown here.
#
# NEVER commit real secrets to version control!
#
# For production deployments, use AWS Secrets Manager or External Secrets
# Operator to inject secrets from external sources.
# ============================================================================

# BEFORE DEPLOYING: Generate secure values for all secrets below
#
# 1. Generate salt (base64-encoded 32 bytes):
#    openssl rand -base64 32
#
# 2. Generate encryption key (64-character hex):
#    openssl rand -hex 32
#
# 3. Generate NextAuth secret (secure random string):
#    openssl rand -base64 32 | tr -d "=+/" | cut -c1-32
#
# 4. Generate database passwords (20 characters each):
#    openssl rand -base64 20 | tr -d "=+/" | cut -c1-20
#
# 5. Generate Redis password:
#    openssl rand -base64 20 | tr -d "=+/" | cut -c1-20
#
# Alternatively, run the generate-secrets.sh script in the repository root
# to generate all required secrets at once.

apiVersion: v1
kind: Secret
metadata:
  name: langfuse
type: Opaque
stringData:
  # Replace with generated salt (base64-encoded 32 bytes)
  salt: "REPLACE_WITH_GENERATED_SALT"

  # Replace with generated encryption key (64-character hex)
  encryption-key: "REPLACE_WITH_GENERATED_ENCRYPTION_KEY"

  # Replace with generated NextAuth secret (32-character alphanumeric)
  nextauth-secret: "REPLACE_WITH_GENERATED_NEXTAUTH_SECRET"

  # Replace with generated PostgreSQL password (20 characters)
  postgresql-password: "REPLACE_WITH_GENERATED_POSTGRES_PASSWORD"

  # Replace with generated ClickHouse password (20 characters)
  clickhouse-password: "REPLACE_WITH_GENERATED_CLICKHOUSE_PASSWORD"

  # Replace with generated Redis password (20 characters)
  redis-password: "REPLACE_WITH_GENERATED_REDIS_PASSWORD"

  # Replace with S3 credentials if using S3 storage
  s3-user: "REPLACE_WITH_S3_USER"
  s3-password: "REPLACE_WITH_S3_PASSWORD"

# For production, consider using External Secrets Operator:
# https://external-secrets.io/latest/provider/aws-secrets-manager/
#
# Example External Secret:
# ---
# apiVersion: external-secrets.io/v1beta1
# kind: ExternalSecret
# metadata:
#   name: langfuse
# spec:
#   refreshInterval: 1h
#   secretStoreRef:
#     name: aws-secrets-manager
#     kind: SecretStore
#   target:
#     name: langfuse
#   data:
#   - secretKey: salt
#     remoteRef:
#       key: aiml-platform/langfuse/salt
#   - secretKey: encryption-key
#     remoteRef:
#       key: aiml-platform/langfuse/encryption-key
