# ============================================================================
# LibreChat Secret Configuration
# ============================================================================
# ⚠️ CRITICAL WARNING: This file contains secret values that MUST be
# generated uniquely for your deployment. DO NOT use the example values.
#
# NEVER commit real secrets to version control!
#
# For production deployments, use AWS Secrets Manager or External Secrets
# Operator to inject secrets from external sources.
# ============================================================================

# BEFORE DEPLOYING: Generate secure values for all secrets below
#
# 1. Generate CREDS_KEY (64-character hex):
#    openssl rand -hex 32
#
# 2. Generate JWT_SECRET (64-character hex):
#    openssl rand -hex 32
#
# 3. Generate JWT_REFRESH_SECRET (64-character hex):
#    openssl rand -hex 32
#
# 4. Generate MEILI_MASTER_KEY (32-character hex):
#    openssl rand -hex 16
#
# 5. AZURE_API_KEY: Obtain from Azure Portal
#    - Go to Azure OpenAI resource → Keys and Endpoint
#    - Copy KEY 1 or KEY 2
#    - DO NOT commit this key to version control!
#
# Alternatively, run the generate-secrets.sh script in the repository root
# to generate random secrets (except Azure API key which must come from Azure).

apiVersion: v1
kind: Secret
metadata:
  name: librechat-credentials-env
  namespace: librechat
type: Opaque
stringData:
  # Credentials encryption key - replace with generated value
  CREDS_KEY: "REPLACE_WITH_GENERATED_CREDS_KEY"

  # JWT secret for authentication - replace with generated value
  JWT_SECRET: "REPLACE_WITH_GENERATED_JWT_SECRET"

  # JWT refresh token secret - replace with generated value
  JWT_REFRESH_SECRET: "REPLACE_WITH_GENERATED_JWT_REFRESH_SECRET"

  # MeiliSearch master key - replace with generated value
  MEILI_MASTER_KEY: "REPLACE_WITH_GENERATED_MEILI_KEY"

  # Azure OpenAI API Key - replace with YOUR Azure API key
  # ⚠️ CRITICAL: Get from Azure Portal, do NOT commit real key to Git
  # If not using Azure OpenAI, you can leave this as placeholder
  AZURE_API_KEY: "REPLACE_WITH_YOUR_AZURE_API_KEY"

# For production, consider using External Secrets Operator:
# https://external-secrets.io/latest/provider/aws-secrets-manager/
#
# Example External Secret:
# ---
# apiVersion: external-secrets.io/v1beta1
# kind: ExternalSecret
# metadata:
#   name: librechat-credentials-env
#   namespace: librechat
# spec:
#   refreshInterval: 1h
#   secretStoreRef:
#     name: aws-secrets-manager
#     kind: SecretStore
#   target:
#     name: librechat-credentials-env
#   data:
#   - secretKey: CREDS_KEY
#     remoteRef:
#       key: aiml-platform/librechat/creds-key
#   - secretKey: AZURE_API_KEY
#     remoteRef:
#       key: aiml-platform/librechat/azure-api-key
