# ============================================================================
# ClusterSecretStore for AWS Secrets Manager
# ============================================================================
# This ClusterSecretStore configures External Secrets Operator to sync secrets
# from AWS Secrets Manager. It uses IRSA (IAM Roles for Service Accounts) for
# authentication, eliminating the need for static credentials.
#
# Prerequisites:
# - External Secrets Operator installed (via Terraform)
# - Service account "external-secrets-sa" with IRSA role annotation
# - IAM role has permissions to read from AWS Secrets Manager
#
# To apply: kubectl apply -f apps/external-secrets-operator/cluster-secret-store.yaml
# To verify: kubectl get clustersecretstore aws-secrets-manager
# To check status: kubectl describe clustersecretstore aws-secrets-manager
# ============================================================================

apiVersion: external-secrets.io/v1beta1
kind: ClusterSecretStore
metadata:
  name: aws-secrets-manager
  labels:
    app: external-secrets-operator
    component: cluster-secret-store
spec:
  provider:
    aws:
      service: SecretsManager
      # AWS region where secrets are stored
      # IMPORTANT: Update this to match your deployment region if not using us-east-1
      region: us-east-1

      # Use IRSA for authentication (no static credentials needed)
      auth:
        jwt:
          serviceAccountRef:
            name: external-secrets-sa
            namespace: external-secrets
